<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Roaster;
use App\Models\Activity;
use Facades\App\Services\Helpers;

class TestController extends Controller
{
    public function test()
    {
        $dataExtracted = [
            [
                'Date' => 'Date',
                'Rev' => 'Rev',
                'DC' => 'DC',
                'C/I(Z)' => 'C/I(Z)',
                'C/O(Z)' => 'C/O(Z)',
                'Activity' => 'Activity',
                'Remark' => 'Remark',
                'From' => 'From',
                'STD(Z)' => 'STD(Z)',
                'To' => 'To',
                'STA(Z)' => 'STA(Z)',
                'AC/Hotel' => 'AC/Hotel',
                'BLH' => 'BLH',
                'Flight Time' => 'Flight Time',
                'Night Time' => 'Night Time',
                'Dur' => 'Dur',
                'Ext' => 'Ext',
                'Pax booked' => 'Pax booked',
                'ACReg' => 'ACReg'
            ],
            [
                'Date' => 'Mon 10',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '0745',
                'C/O(Z)' => '',
                'Activity' => 'DX77',
                'Remark' => 'DX 0077',
                'From' => 'KRP',
                'STD(Z)' => '0845',
                'To' => 'CPH',
                'STA(Z)' => '0935',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX80',
                'Remark' => 'DX 0080',
                'From' => 'CPH',
                'STD(Z)' => '1345',
                'To' => 'KRP',
                'STA(Z)' => '1435',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX83',
                'Remark' => 'DX 0083',
                'From' => 'KRP',
                'STD(Z)' => '1520',
                'To' => 'CPH',
                'STA(Z)' => '1610',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '1755',
                'Activity' => 'DX82',
                'Remark' => 'DX 0082',
                'From' => 'CPH',
                'STD(Z)' => '1645',
                'To' => 'KRP',
                'STA(Z)' => '1735',
                'AC/Hotel' => 'DO4',
                'BLH' => '3:20',
                'Flight Time' => '0:50',
                'Night Time' => '',
                'Dur' => '10:10',
                'Ext' => '0',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => 'Tue 11',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '0745',
                'C/O(Z)' => '',
                'Activity' => 'DX77',
                'Remark' => 'DX 0077',
                'From' => 'KRP',
                'STD(Z)' => '0845',
                'To' => 'CPH',
                'STA(Z)' => '0935',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX80',
                'Remark' => 'DX 0080',
                'From' => 'CPH',
                'STD(Z)' => '1345',
                'To' => 'KRP',
                'STA(Z)' => '1435',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX83',
                'Remark' => 'DX 0083',
                'From' => 'KRP',
                'STD(Z)' => '1520',
                'To' => 'CPH',
                'STA(Z)' => '1610',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '1755',
                'Activity' => 'DX82',
                'Remark' => 'DX 0082',
                'From' => 'CPH',
                'STD(Z)' => '1645',
                'To' => 'KRP',
                'STA(Z)' => '1735',
                'AC/Hotel' => 'DO4',
                'BLH' => '3:20',
                'Flight Time' => '0:50',
                'Night Time' => '',
                'Dur' => '10:10',
                'Ext' => '0',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => 'Wed 12',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'OFF',
                'Remark' => 'OFF',
                'From' => 'KRP',
                'STD(Z)' => '2300-1',
                'To' => 'KRP',
                'STA(Z)' => '2300',
                'AC/Hotel' => '',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => ''
            ],
            [
                'Date' => 'Thu 13',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'OFF',
                'Remark' => 'OFF',
                'From' => 'KRP',
                'STD(Z)' => '2300-1',
                'To' => 'KRP',
                'STA(Z)' => '2300',
                'AC/Hotel' => '',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => ''
            ],
            [
                'Date' => 'Fri 14',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'OFF',
                'Remark' => 'OFF',
                'From' => 'KRP',
                'STD(Z)' => '2300-1',
                'To' => 'KRP',
                'STA(Z)' => '2300',
                'AC/Hotel' => '',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => ''
            ],
            [
                'Date' => 'Sat 15',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '0500',
                'C/O(Z)' => '1700',
                'Activity' => 'SBY',
                'Remark' => 'SBY',
                'From' => 'KRP',
                'STD(Z)' => '0500',
                'To' => 'KRP',
                'STA(Z)' => '1700',
                'AC/Hotel' => '',
                'BLH' => '0:00',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '3:00',
                'Ext' => '0',
                'Pax booked' => '',
                'ACReg' => ''
            ],
            [
                'Date' => 'Sun 16',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '0500',
                'C/O(Z)' => '1700',
                'Activity' => 'SBY',
                'Remark' => 'SBY',
                'From' => 'KRP',
                'STD(Z)' => '0500',
                'To' => 'KRP',
                'STA(Z)' => '1700',
                'AC/Hotel' => '',
                'BLH' => '0:00',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '3:00',
                'Ext' => '0',
                'Pax booked' => '',
                'ACReg' => ''
            ],
            [
                'Date' => 'Mon 17',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '0745',
                'C/O(Z)' => '',
                'Activity' => 'DX77',
                'Remark' => 'DX 0077',
                'From' => 'KRP',
                'STD(Z)' => '0845',
                'To' => 'CPH',
                'STA(Z)' => '0935',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX80',
                'Remark' => 'DX 0080',
                'From' => 'CPH',
                'STD(Z)' => '1345',
                'To' => 'KRP',
                'STA(Z)' => '1435',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX83',
                'Remark' => 'DX 0083',
                'From' => 'KRP',
                'STD(Z)' => '1520',
                'To' => 'CPH',
                'STA(Z)' => '1610',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '1755',
                'Activity' => 'DX82',
                'Remark' => 'DX 0082',
                'From' => 'CPH',
                'STD(Z)' => '1645',
                'To' => 'KRP',
                'STA(Z)' => '1735',
                'AC/Hotel' => 'DO4',
                'BLH' => '3:20',
                'Flight Time' => '0:50',
                'Night Time' => '',
                'Dur' => '10:10',
                'Ext' => '0',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => 'Tue 18',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'OFF',
                'Remark' => 'OFF',
                'From' => 'KRP',
                'STD(Z)' => '2300-1',
                'To' => 'KRP',
                'STA(Z)' => '2300',
                'AC/Hotel' => '',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => ''
            ],
            [
                'Date' => 'Wed 19',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'OFF',
                'Remark' => 'OFF',
                'From' => 'KRP',
                'STD(Z)' => '2300-1',
                'To' => 'KRP',
                'STA(Z)' => '2300',
                'AC/Hotel' => '',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => ''
            ],
            [
                'Date' => 'Thu 20',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '0500',
                'C/O(Z)' => '',
                'Activity' => 'DX73',
                'Remark' => 'DX 0073',
                'From' => 'KRP',
                'STD(Z)' => '0600',
                'To' => 'CPH',
                'STA(Z)' => '0650',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX74',
                'Remark' => 'DX 0074',
                'From' => 'CPH',
                'STD(Z)' => '0720',
                'To' => 'KRP',
                'STA(Z)' => '0810',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX77',
                'Remark' => 'DX 0077',
                'From' => 'KRP',
                'STD(Z)' => '0845',
                'To' => 'CPH',
                'STA(Z)' => '0935',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '1430',
                'Activity' => 'DX80',
                'Remark' => 'DX 0080',
                'From' => 'CPH',
                'STD(Z)' => '1315',
                'To' => 'KRP',
                'STA(Z)' => '1410',
                'AC/Hotel' => 'DO4',
                'BLH' => '3:25',
                'Flight Time' => '0:55',
                'Night Time' => '',
                'Dur' => '9:30',
                'Ext' => '0',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => 'Fri 21',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '0500',
                'C/O(Z)' => '',
                'Activity' => 'DX73',
                'Remark' => 'DX 0073',
                'From' => 'KRP',
                'STD(Z)' => '0600',
                'To' => 'CPH',
                'STA(Z)' => '0650',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX74',
                'Remark' => 'DX 0074',
                'From' => 'CPH',
                'STD(Z)' => '0720',
                'To' => 'KRP',
                'STA(Z)' => '0810',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX77',
                'Remark' => 'DX 0077',
                'From' => 'KRP',
                'STD(Z)' => '0845',
                'To' => 'CPH',
                'STA(Z)' => '0935',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '1500',
                'Activity' => 'DX80',
                'Remark' => 'DX 0080',
                'From' => 'CPH',
                'STD(Z)' => '1345',
                'To' => 'KRP',
                'STA(Z)' => '1440',
                'AC/Hotel' => 'DO4',
                'BLH' => '3:25',
                'Flight Time' => '0:55',
                'Night Time' => '',
                'Dur' => '10:00',
                'Ext' => '0',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => 'Sat 22',
                'Rev' => '',
                'DC' => 'DH',
                'C/I(Z)' => '0555',
                'C/O(Z)' => '',
                'Activity' => 'CAR',
                'Remark' => 'Comapany Car',
                'From' => 'KRP',
                'STD(Z)' => '0555',
                'To' => 'EBJ',
                'STA(Z)' => '0720',
                'AC/Hotel' => '',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => ''
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '0720',
                'C/O(Z)' => '',
                'Activity' => 'DX21',
                'Remark' => 'DX 0021',
                'From' => 'EBJ',
                'STD(Z)' => '0820',
                'To' => 'SVG',
                'STA(Z)' => '0930',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRJ'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX22',
                'Remark' => 'DX 0022',
                'From' => 'SVG',
                'STD(Z)' => '1000',
                'To' => 'EBJ',
                'STA(Z)' => '1110',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRJ'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => 'DH',
                'C/I(Z)' => '',
                'C/O(Z)' => '1310',
                'Activity' => 'CAR',
                'Remark' => 'Company Car',
                'From' => 'EBJ',
                'STD(Z)' => '1130',
                'To' => 'KRP',
                'STA(Z)' => '1310',
                'AC/Hotel' => '',
                'BLH' => '2:20',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '7:15',
                'Ext' => '0',
                'Pax booked' => '',
                'ACReg' => ''
            ],
            [
                'Date' => 'Sun 23',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '0945',
                'C/O(Z)' => '',
                'Activity' => 'DX79',
                'Remark' => 'DX 0079',
                'From' => 'KRP',
                'STD(Z)' => '1045',
                'To' => 'CPH',
                'STA(Z)' => '1135',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX82',
                'Remark' => 'DX 0082',
                'From' => 'CPH',
                'STD(Z)' => '1600',
                'To' => 'KRP',
                'STA(Z)' => '1650',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '',
                'Activity' => 'DX85',
                'Remark' => 'DX 0085',
                'From' => 'KRP',
                'STD(Z)' => '1720',
                'To' => 'CPH',
                'STA(Z)' => '1810',
                'AC/Hotel' => 'DO4',
                'BLH' => '',
                'Flight Time' => '',
                'Night Time' => '',
                'Dur' => '',
                'Ext' => '',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ],
            [
                'Date' => '',
                'Rev' => '',
                'DC' => '',
                'C/I(Z)' => '',
                'C/O(Z)' => '1950',
                'Activity' => 'DX86',
                'Remark' => 'DX 0086',
                'From' => 'CPH',
                'STD(Z)' => '1840',
                'To' => 'KRP',
                'STA(Z)' => '1930',
                'AC/Hotel' => 'DO4',
                'BLH' => '3:20',
                'Flight Time' => '0:50',
                'Night Time' => '',
                'Dur' => '10:05',
                'Ext' => '0',
                'Pax booked' => '',
                'ACReg' => 'OYJRY'
            ]
        ];

        $data = [];
        $currentDate = null;
        $checkin = null;
        $checkout = null;
        $keystart = null;
        $keyend = null;

        foreach ($dataExtracted as $k => $row) {
            if (!empty($row['Date'])) {
                if (!is_null($currentDate)) {
                    // Store the previous day's data
                    $data[] = [
                        'date' => $currentDate,
                        'checkin' => $checkin,
                        'checkout' => $checkout,
                        'keystart' => $keystart,
                        'keyend' => $keyend
                    ];
                }

                // Update the current date
                $currentDate = $row['Date'];
                // Reset checkin, checkout, keystart, and keyend
                $checkin = null;
                $checkout = null;
                $keystart = null;
                $keyend = null;
            }

            if (!empty($row['C/I(Z)']) && empty($checkin)) {
                $checkin = $row['C/I(Z)'];
            }

            if (empty($keystart)) {
                $keystart = $k;
            }

            if (!empty($row['C/O(Z)'])) {
                $checkout = $row['C/O(Z)'];
            }

            $keyend = $k;
        }

        // Add the last day's data
        $data[] = [
            'date' => $currentDate,
            'checkin' => $checkin,
            'checkout' => $checkout,
            'keystart' => $keystart,
            'keyend' => $keyend
        ];

        // dd($data);

        foreach ($data as $k => $d) {
            if ($k > 0) {

                // dd(Helpers::getDateFromDay($d['date']),
                //     Helpers::convertToTimeFormat($d['checkin']),
                //     Helpers::convertToTimeFormat(''),
                //     Helpers::convertToTimeFormat($d['checkout']));

                $roaster = Roaster::create([
                    'date' => Helpers::getDateFromDay($d['date']),
                    'check_in' => Helpers::convertToTimeFormat($d['checkin']),
                    'check_out' => Helpers::convertToTimeFormat($d['checkout']),
                ]);

                // dd($d['keystart'], $d['keyend'], $dataExtracted[$d['keystart']]['Activity']);

                for ($i = $d['keystart']; $i <= $d['keyend']; $i++) {

                    // dd($i, $dataExtracted[$i]['Activity']);

                    $activity = $dataExtracted[$i];

                    // dd($activity);

                    Activity::create([
                        'roaster_id' => $roaster->id,
                        'activity' => $activity['Activity'],
                        'code' => $activity['Remark'],
                        'from' => $activity['From'],
                        'std' => $activity['STD(Z)'],
                        'to' => $activity['To'],
                        'sta' => $activity['STA(Z)'],
                        'remarks' => $activity['AC/Hotel'],
                        'blh' => $activity['BLH'],
                        'flight_time' => $activity['Flight Time'],
                        'night_time' => $activity['Night Time'],
                        'duration' => $activity['Dur'],
                        'ext' => $activity['Ext'],
                        'pax_booked' => $activity['Pax booked'],
                        'ac_reg' => $activity['ACReg'],
                    ]);
                }
            }
        }

        dd('Data inserted successfully!');

        return view('test');
    }
}
